spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: Hs!23456
    filters: log4j,wall,mergeStat
    hikari:
      readOnly: false
      connectionTimeout: 30000 # 等待来自连接池的连接 默认30秒
      idleTimeout: 600000 # 连接允许在连接池中闲置的时间 默认10分钟
      validationTimeout: 5000 # 连接将被测试活动的最大时间量
      maxLifetime: 1800000 # 连接池中连接最大的生命周期 默认30分钟
      loginTimeout: 10 # 连接超时间件
      maximumPoolSize: 20 # 最大的可用连接
      minimumIdle: 10 # 最小的连接
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms  # 连接超时时长（毫秒）