beam:
  admin:
    swagger-open: true  #是否开启swagger (true/false)
    kaptcha-open: false
    redis-open: false  # 是否开启redis缓存  true开启   false关闭
    shiro-redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
    version: 0.0.1
server:
   port: 8080
   tomcat:
     uri-encoding: UTF-8
     max-threads: 1000
     min-spare-threads: 30
   servlet:
     context-path: /beam_ht
log:
  path: beam-admin-logs
